fully separate core metrics
specklesystems/specklepy pull request #287
Opened 2023-07-11 23:08 UTC by KatKatKateryna

2023-07-20 13:57 UTC, gjedlicska commented
Lets try to follow PEP8 in naming and style conventions: https://peps.python.org/pep-0008/

Class names should be CapitalCase, eg `Core_Resource` should be `CoreResource`

2023-07-20 14:27 UTC, gjedlicska reviewed
I've left some notes, mostly stylistic changes. The important parts look good

2023-07-20 14:27 UTC, gjedlicska commented on src/specklepy/api/host_applications.py
>  class HostApplication:
This definition can be a re-export from core too

2023-07-20 14:27 UTC, gjedlicska commented on src/specklepy/api/host_applications.py
>  def get_host_app_from_string(app_name: str) -> HostApplication:
this is a re-export too

2023-07-20 14:27 UTC, gjedlicska commented on src/specklepy/api/host_applications.py
>  _app_name_host_app_mapping = {
this is prob not needed after importing everything from core

2023-07-20 14:27 UTC, gjedlicska commented on src/specklepy/api/credentials.py
> +class Account(BaseModel):
This can be imported from core

2023-07-20 14:27 UTC, gjedlicska commented on src/specklepy/api/resources/stream.py
>      @deprecated(
lets delete this definition. It has been deprecated for a while.

2023-07-20 14:27 UTC, gjedlicska commented on src/specklepy/api/resources/user.py
> +class Resource(Core_Resource):
Lets delete this class and module, it's been deprecated for a while now

2023-07-20 14:28 UTC, gjedlicska requested changes
Lets make the few noted changes

2023-07-25 16:18 UTC, KatKatKateryna commented
@gjedlicska changes applied except the 'user' resource - will be deprecated in 2.16

2023-07-26 07:04 UTC, gjedlicska approved these changes

2023-07-26 15:19 UTC, merged