feat(v-3): QGIS essentials
specklesystems/specklepy pull request #369
Opened 2024-12-13 14:45 UTC by dogukankaratas

adds QGIS essentials.

Geometry:
- Polyline
- Mesh

Interface:
- IHasArea
- IHasVolume

Proxies:
- InstanceProxy
- InstanceDefinitionProxy
- ColorProxy
- GroupProxy

2024-12-15 22:28 UTC, KatKatKateryna requested changes
I went a bit too detailed, but hopefully we won't need to touch these again!

Some other comments not related to this specific commit, but related to the new objects: 
- Point class "distance_to" ignores Point units (extra test can reveal it). Also a problem in C# 
- Line method "from_coords" doesn't exist in C#

2024-12-15 22:28 UTC, KatKatKateryna commented on src/specklepy/objects/tests/mesh_test.py
> +from specklepy.api.operations import deserialize, serialize
applicable to all test files: we can import "operations" module from core.api instead, to avoid unnecessary user-facing calls

2024-12-15 22:28 UTC, KatKatKateryna commented on src/specklepy/objects/proxies.py
> +    name: str = field(default="Unnamed Group")
no default value in C#

2024-12-15 22:28 UTC, KatKatKateryna commented on src/specklepy/objects/proxies.py
> +    objects: List[str] = field(default_factory=list)
no default value in C#

2024-12-15 22:28 UTC, KatKatKateryna commented on src/specklepy/objects/proxies.py
> +    objects: List[str] = field(default_factory=list)
no default value in C#

2024-12-15 22:28 UTC, KatKatKateryna commented on src/specklepy/objects/proxies.py
> +    max_depth: int = 50
no default value in C#

2024-12-15 22:28 UTC, KatKatKateryna commented on src/specklepy/objects/proxies.py
> +    transform: List[float] = field(default_factory=list)
no default value in C#

2024-12-15 22:28 UTC, KatKatKateryna commented on src/specklepy/objects/proxies.py
> +    name: str = field(default="Unnamed Instance")
all 3 properties have no defaults in C#

2024-12-15 22:29 UTC, KatKatKateryna commented
Formatting PR (you can ignore it and format yourself after changes, if you prefer): https://github.com/specklesystems/specklepy/pull/370

2024-12-17 12:05 UTC, dogukankaratas commented on src/specklepy/objects/geometry.py
> +    def from_list(cls, coords: List[float], units: str | Units) -> "Polyline":
I decided to keep units as a seperate argument to be able to compatible with all the classes.

2024-12-17 12:06 UTC, dogukankaratas commented
> I went a bit too detailed, but hopefully we won't need to touch these again!
> 
> Some other comments not related to this specific commit, but related to the new objects:
> 
> * Point class "distance_to" ignores Point units (extra test can reveal it). Also a problem in C#
> * Line method "from_coords" doesn't exist in C#

Fixed.

2024-12-17 12:19 UTC, KatKatKateryna approved these changes

2025-01-07 00:41 UTC, KatKatKateryna commented
this is good to merge, right?

2025-01-07 09:38 UTC, merged